### ISSUE TITLE
How to Half turn

### ISSUE THREAD

**Issue by sajovicd** [udivankin/Stepper2#3]
Hello,
I found this library very useful in my fish feeder project, but I dont know hot to turn motor for only half revolution or something that is not full revolution.

I would like to turn clockwise 2 revolution and counterclockwise half revolution.
How to achieve that?

Thanks in advance

**Comment by tobymurray** [comment]
Knowing that `stepsPerFullTurn = 4096;` and that `4096/2 = 2048`, `step(2048)` would be a half turn.

**Comment by sajovicd** [comment]
I found that steps setting later, but forgot to mention that here...
Thanks anyway
It is great library.

**Comment by tobymurray** [comment]
If you're satisfied with the answer, I'd recommend closing this issue.
